CREATE TABLE IF NOT EXISTS `workspaces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `slug` VARCHAR(50) NOT NULL,
  `created_by` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  UNIQUE KEY (`slug`),
  FOREIGN KEY (`created_by`) REFERENCES users(`id`),
  INDEX idx_workspaces_created_by (`created_by`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4
