dir: '{{.InterfaceDir}}/mocks/'
structname: '{{.InterfaceName}}'
pkgname: mocks
template: testify
filename: '{{.InterfaceName}}.go'
packages:
  github.com/rm-ryou/mococoplan/internal/core/ports:
    interfaces:
      TokenIssuer: {}
      TokenVerifier: {}
      AuthServicer: {}
      UserRepository: {}
      SessionRepository: {}
      TxManager: {}
      WorkspaceServicer: {}
      WorkspaceRepository: {}
      WorkspaceMemberRepository: {}

