// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rm-ryou/mococoplan/internal/core/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewServicer creates a new instance of Servicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Servicer {
	mock := &Servicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Servicer is an autogenerated mock type for the Servicer type
type Servicer struct {
	mock.Mock
}

type Servicer_Expecter struct {
	mock *mock.Mock
}

func (_m *Servicer) EXPECT() *Servicer_Expecter {
	return &Servicer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Servicer
func (_mock *Servicer) Create(ctx context.Context, cmd *user.CreateCmd) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateCmd) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Servicer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Servicer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *user.CreateCmd
func (_e *Servicer_Expecter) Create(ctx interface{}, cmd interface{}) *Servicer_Create_Call {
	return &Servicer_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *Servicer_Create_Call) Run(run func(ctx context.Context, cmd *user.CreateCmd)) *Servicer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.CreateCmd
		if args[1] != nil {
			arg1 = args[1].(*user.CreateCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Servicer_Create_Call) Return(err error) *Servicer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Servicer_Create_Call) RunAndReturn(run func(ctx context.Context, cmd *user.CreateCmd) error) *Servicer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Repository
func (_mock *Repository) Create(ctx context.Context, u *user.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.User
func (_e *Repository_Expecter) Create(ctx interface{}, u interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, u *user.User)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Create_Call) Return(err error) *Repository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(ctx context.Context, u *user.User) error) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type Repository
func (_mock *Repository) FindByEmail(ctx context.Context, email string) (*user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type Repository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Repository_Expecter) FindByEmail(ctx interface{}, email interface{}) *Repository_FindByEmail_Call {
	return &Repository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *Repository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *Repository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_FindByEmail_Call) Return(user1 *user.User, err error) *Repository_FindByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *Repository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*user.User, error)) *Repository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}
