// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rm-ryou/mococoplan/internal/core/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthServicer creates a new instance of AuthServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServicer {
	mock := &AuthServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthServicer is an autogenerated mock type for the AuthServicer type
type AuthServicer struct {
	mock.Mock
}

type AuthServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServicer) EXPECT() *AuthServicer_Expecter {
	return &AuthServicer_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type AuthServicer
func (_mock *AuthServicer) Login(ctx context.Context, cmd *ports.LoginCmd) (*ports.AuthResult, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *ports.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.LoginCmd) (*ports.AuthResult, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.LoginCmd) *ports.AuthResult); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ports.LoginCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServicer_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthServicer_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *ports.LoginCmd
func (_e *AuthServicer_Expecter) Login(ctx interface{}, cmd interface{}) *AuthServicer_Login_Call {
	return &AuthServicer_Login_Call{Call: _e.mock.On("Login", ctx, cmd)}
}

func (_c *AuthServicer_Login_Call) Run(run func(ctx context.Context, cmd *ports.LoginCmd)) *AuthServicer_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ports.LoginCmd
		if args[1] != nil {
			arg1 = args[1].(*ports.LoginCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServicer_Login_Call) Return(authResult *ports.AuthResult, err error) *AuthServicer_Login_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *AuthServicer_Login_Call) RunAndReturn(run func(ctx context.Context, cmd *ports.LoginCmd) (*ports.AuthResult, error)) *AuthServicer_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthServicer
func (_mock *AuthServicer) Logout(ctx context.Context, cmd *ports.LogoutCmd) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.LogoutCmd) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServicer_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthServicer_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *ports.LogoutCmd
func (_e *AuthServicer_Expecter) Logout(ctx interface{}, cmd interface{}) *AuthServicer_Logout_Call {
	return &AuthServicer_Logout_Call{Call: _e.mock.On("Logout", ctx, cmd)}
}

func (_c *AuthServicer_Logout_Call) Run(run func(ctx context.Context, cmd *ports.LogoutCmd)) *AuthServicer_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ports.LogoutCmd
		if args[1] != nil {
			arg1 = args[1].(*ports.LogoutCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServicer_Logout_Call) Return(err error) *AuthServicer_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServicer_Logout_Call) RunAndReturn(run func(ctx context.Context, cmd *ports.LogoutCmd) error) *AuthServicer_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Signup provides a mock function for the type AuthServicer
func (_mock *AuthServicer) Signup(ctx context.Context, cmd *ports.SignupCmd) (*ports.AuthResult, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Signup")
	}

	var r0 *ports.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.SignupCmd) (*ports.AuthResult, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.SignupCmd) *ports.AuthResult); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ports.SignupCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServicer_Signup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signup'
type AuthServicer_Signup_Call struct {
	*mock.Call
}

// Signup is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *ports.SignupCmd
func (_e *AuthServicer_Expecter) Signup(ctx interface{}, cmd interface{}) *AuthServicer_Signup_Call {
	return &AuthServicer_Signup_Call{Call: _e.mock.On("Signup", ctx, cmd)}
}

func (_c *AuthServicer_Signup_Call) Run(run func(ctx context.Context, cmd *ports.SignupCmd)) *AuthServicer_Signup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ports.SignupCmd
		if args[1] != nil {
			arg1 = args[1].(*ports.SignupCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServicer_Signup_Call) Return(authResult *ports.AuthResult, err error) *AuthServicer_Signup_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *AuthServicer_Signup_Call) RunAndReturn(run func(ctx context.Context, cmd *ports.SignupCmd) (*ports.AuthResult, error)) *AuthServicer_Signup_Call {
	_c.Call.Return(run)
	return _c
}
