// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rm-ryou/mococoplan/internal/core/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) Issue(identity *ports.UserIdentity) (*ports.AccessToken, error) {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 *ports.AccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ports.UserIdentity) (*ports.AccessToken, error)); ok {
		return returnFunc(identity)
	}
	if returnFunc, ok := ret.Get(0).(func(*ports.UserIdentity) *ports.AccessToken); ok {
		r0 = returnFunc(identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.AccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ports.UserIdentity) error); ok {
		r1 = returnFunc(identity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - identity *ports.UserIdentity
func (_e *TokenIssuer_Expecter) Issue(identity interface{}) *TokenIssuer_Issue_Call {
	return &TokenIssuer_Issue_Call{Call: _e.mock.On("Issue", identity)}
}

func (_c *TokenIssuer_Issue_Call) Run(run func(identity *ports.UserIdentity)) *TokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ports.UserIdentity
		if args[0] != nil {
			arg0 = args[0].(*ports.UserIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenIssuer_Issue_Call) Return(accessToken *ports.AccessToken, err error) *TokenIssuer_Issue_Call {
	_c.Call.Return(accessToken, err)
	return _c
}

func (_c *TokenIssuer_Issue_Call) RunAndReturn(run func(identity *ports.UserIdentity) (*ports.AccessToken, error)) *TokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}
