// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rm-ryou/mococoplan/internal/core/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenVerifier creates a new instance of TokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenVerifier {
	mock := &TokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenVerifier is an autogenerated mock type for the TokenVerifier type
type TokenVerifier struct {
	mock.Mock
}

type TokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenVerifier) EXPECT() *TokenVerifier_Expecter {
	return &TokenVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type TokenVerifier
func (_mock *TokenVerifier) Verify(token string) (*ports.UserIdentity, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *ports.UserIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*ports.UserIdentity, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ports.UserIdentity); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.UserIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *TokenVerifier_Expecter) Verify(token interface{}) *TokenVerifier_Verify_Call {
	return &TokenVerifier_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *TokenVerifier_Verify_Call) Run(run func(token string)) *TokenVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenVerifier_Verify_Call) Return(userIdentity *ports.UserIdentity, err error) *TokenVerifier_Verify_Call {
	_c.Call.Return(userIdentity, err)
	return _c
}

func (_c *TokenVerifier_Verify_Call) RunAndReturn(run func(token string) (*ports.UserIdentity, error)) *TokenVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
