// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	"github.com/rm-ryou/mococoplan/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkspaceRepository creates a new instance of WorkspaceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceRepository {
	mock := &WorkspaceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkspaceRepository is an autogenerated mock type for the WorkspaceRepository type
type WorkspaceRepository struct {
	mock.Mock
}

type WorkspaceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkspaceRepository) EXPECT() *WorkspaceRepository_Expecter {
	return &WorkspaceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type WorkspaceRepository
func (_mock *WorkspaceRepository) Create(ctx context.Context, tx *sql.Tx, ws *domain.Workspace) (int, error) {
	ret := _mock.Called(ctx, tx, ws)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, *domain.Workspace) (int, error)); ok {
		return returnFunc(ctx, tx, ws)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, *domain.Workspace) int); ok {
		r0 = returnFunc(ctx, tx, ws)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, *domain.Workspace) error); ok {
		r1 = returnFunc(ctx, tx, ws)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WorkspaceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - ws *domain.Workspace
func (_e *WorkspaceRepository_Expecter) Create(ctx interface{}, tx interface{}, ws interface{}) *WorkspaceRepository_Create_Call {
	return &WorkspaceRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, ws)}
}

func (_c *WorkspaceRepository_Create_Call) Run(run func(ctx context.Context, tx *sql.Tx, ws *domain.Workspace)) *WorkspaceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 *domain.Workspace
		if args[2] != nil {
			arg2 = args[2].(*domain.Workspace)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkspaceRepository_Create_Call) Return(n int, err error) *WorkspaceRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *WorkspaceRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, ws *domain.Workspace) (int, error)) *WorkspaceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type WorkspaceRepository
func (_mock *WorkspaceRepository) FindByID(ctx context.Context, workspaceID int) (*domain.Workspace, error) {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.Workspace, error)); ok {
		return returnFunc(ctx, workspaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.Workspace); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type WorkspaceRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID int
func (_e *WorkspaceRepository_Expecter) FindByID(ctx interface{}, workspaceID interface{}) *WorkspaceRepository_FindByID_Call {
	return &WorkspaceRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, workspaceID)}
}

func (_c *WorkspaceRepository_FindByID_Call) Run(run func(ctx context.Context, workspaceID int)) *WorkspaceRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkspaceRepository_FindByID_Call) Return(workspace *domain.Workspace, err error) *WorkspaceRepository_FindByID_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *WorkspaceRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, workspaceID int) (*domain.Workspace, error)) *WorkspaceRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type WorkspaceRepository
func (_mock *WorkspaceRepository) ListByUser(ctx context.Context, userID int) ([]*domain.Workspace, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*domain.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Workspace, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*domain.Workspace); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type WorkspaceRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *WorkspaceRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *WorkspaceRepository_ListByUser_Call {
	return &WorkspaceRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *WorkspaceRepository_ListByUser_Call) Run(run func(ctx context.Context, userID int)) *WorkspaceRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkspaceRepository_ListByUser_Call) Return(workspaces []*domain.Workspace, err error) *WorkspaceRepository_ListByUser_Call {
	_c.Call.Return(workspaces, err)
	return _c
}

func (_c *WorkspaceRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*domain.Workspace, error)) *WorkspaceRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
