// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rm-ryou/mococoplan/internal/core/domain"
	"github.com/rm-ryou/mococoplan/internal/core/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkspaceServicer creates a new instance of WorkspaceServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceServicer {
	mock := &WorkspaceServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkspaceServicer is an autogenerated mock type for the WorkspaceServicer type
type WorkspaceServicer struct {
	mock.Mock
}

type WorkspaceServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkspaceServicer) EXPECT() *WorkspaceServicer_Expecter {
	return &WorkspaceServicer_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function for the type WorkspaceServicer
func (_mock *WorkspaceServicer) AddMember(ctx context.Context, cmd *ports.AddWorkspaceMemberCmd) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.AddWorkspaceMemberCmd) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkspaceServicer_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type WorkspaceServicer_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *ports.AddWorkspaceMemberCmd
func (_e *WorkspaceServicer_Expecter) AddMember(ctx interface{}, cmd interface{}) *WorkspaceServicer_AddMember_Call {
	return &WorkspaceServicer_AddMember_Call{Call: _e.mock.On("AddMember", ctx, cmd)}
}

func (_c *WorkspaceServicer_AddMember_Call) Run(run func(ctx context.Context, cmd *ports.AddWorkspaceMemberCmd)) *WorkspaceServicer_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ports.AddWorkspaceMemberCmd
		if args[1] != nil {
			arg1 = args[1].(*ports.AddWorkspaceMemberCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkspaceServicer_AddMember_Call) Return(err error) *WorkspaceServicer_AddMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkspaceServicer_AddMember_Call) RunAndReturn(run func(ctx context.Context, cmd *ports.AddWorkspaceMemberCmd) error) *WorkspaceServicer_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type WorkspaceServicer
func (_mock *WorkspaceServicer) Create(ctx context.Context, cmd *ports.CreateWorkspaceCmd) (*domain.Workspace, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.CreateWorkspaceCmd) (*domain.Workspace, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.CreateWorkspaceCmd) *domain.Workspace); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ports.CreateWorkspaceCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceServicer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WorkspaceServicer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *ports.CreateWorkspaceCmd
func (_e *WorkspaceServicer_Expecter) Create(ctx interface{}, cmd interface{}) *WorkspaceServicer_Create_Call {
	return &WorkspaceServicer_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *WorkspaceServicer_Create_Call) Run(run func(ctx context.Context, cmd *ports.CreateWorkspaceCmd)) *WorkspaceServicer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ports.CreateWorkspaceCmd
		if args[1] != nil {
			arg1 = args[1].(*ports.CreateWorkspaceCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkspaceServicer_Create_Call) Return(workspace *domain.Workspace, err error) *WorkspaceServicer_Create_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *WorkspaceServicer_Create_Call) RunAndReturn(run func(ctx context.Context, cmd *ports.CreateWorkspaceCmd) (*domain.Workspace, error)) *WorkspaceServicer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function for the type WorkspaceServicer
func (_mock *WorkspaceServicer) ListMembers(ctx context.Context, workspaceID int, userID int) ([]*domain.WorkspaceMember, error) {
	ret := _mock.Called(ctx, workspaceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []*domain.WorkspaceMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.WorkspaceMember, error)); ok {
		return returnFunc(ctx, workspaceID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.WorkspaceMember); ok {
		r0 = returnFunc(ctx, workspaceID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WorkspaceMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, workspaceID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceServicer_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type WorkspaceServicer_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID int
//   - userID int
func (_e *WorkspaceServicer_Expecter) ListMembers(ctx interface{}, workspaceID interface{}, userID interface{}) *WorkspaceServicer_ListMembers_Call {
	return &WorkspaceServicer_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, workspaceID, userID)}
}

func (_c *WorkspaceServicer_ListMembers_Call) Run(run func(ctx context.Context, workspaceID int, userID int)) *WorkspaceServicer_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkspaceServicer_ListMembers_Call) Return(workspaceMembers []*domain.WorkspaceMember, err error) *WorkspaceServicer_ListMembers_Call {
	_c.Call.Return(workspaceMembers, err)
	return _c
}

func (_c *WorkspaceServicer_ListMembers_Call) RunAndReturn(run func(ctx context.Context, workspaceID int, userID int) ([]*domain.WorkspaceMember, error)) *WorkspaceServicer_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaces provides a mock function for the type WorkspaceServicer
func (_mock *WorkspaceServicer) ListWorkspaces(ctx context.Context, userID int) ([]*domain.Workspace, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaces")
	}

	var r0 []*domain.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Workspace, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*domain.Workspace); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceServicer_ListWorkspaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaces'
type WorkspaceServicer_ListWorkspaces_Call struct {
	*mock.Call
}

// ListWorkspaces is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *WorkspaceServicer_Expecter) ListWorkspaces(ctx interface{}, userID interface{}) *WorkspaceServicer_ListWorkspaces_Call {
	return &WorkspaceServicer_ListWorkspaces_Call{Call: _e.mock.On("ListWorkspaces", ctx, userID)}
}

func (_c *WorkspaceServicer_ListWorkspaces_Call) Run(run func(ctx context.Context, userID int)) *WorkspaceServicer_ListWorkspaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkspaceServicer_ListWorkspaces_Call) Return(workspaces []*domain.Workspace, err error) *WorkspaceServicer_ListWorkspaces_Call {
	_c.Call.Return(workspaces, err)
	return _c
}

func (_c *WorkspaceServicer_ListWorkspaces_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*domain.Workspace, error)) *WorkspaceServicer_ListWorkspaces_Call {
	_c.Call.Return(run)
	return _c
}
