// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	"github.com/rm-ryou/mococoplan/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkspaceMemberRepository creates a new instance of WorkspaceMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceMemberRepository {
	mock := &WorkspaceMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkspaceMemberRepository is an autogenerated mock type for the WorkspaceMemberRepository type
type WorkspaceMemberRepository struct {
	mock.Mock
}

type WorkspaceMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkspaceMemberRepository) EXPECT() *WorkspaceMemberRepository_Expecter {
	return &WorkspaceMemberRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type WorkspaceMemberRepository
func (_mock *WorkspaceMemberRepository) Add(ctx context.Context, tx *sql.Tx, m *domain.WorkspaceMember) error {
	ret := _mock.Called(ctx, tx, m)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, *domain.WorkspaceMember) error); ok {
		r0 = returnFunc(ctx, tx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkspaceMemberRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type WorkspaceMemberRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - m *domain.WorkspaceMember
func (_e *WorkspaceMemberRepository_Expecter) Add(ctx interface{}, tx interface{}, m interface{}) *WorkspaceMemberRepository_Add_Call {
	return &WorkspaceMemberRepository_Add_Call{Call: _e.mock.On("Add", ctx, tx, m)}
}

func (_c *WorkspaceMemberRepository_Add_Call) Run(run func(ctx context.Context, tx *sql.Tx, m *domain.WorkspaceMember)) *WorkspaceMemberRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 *domain.WorkspaceMember
		if args[2] != nil {
			arg2 = args[2].(*domain.WorkspaceMember)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkspaceMemberRepository_Add_Call) Return(err error) *WorkspaceMemberRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkspaceMemberRepository_Add_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, m *domain.WorkspaceMember) error) *WorkspaceMemberRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type WorkspaceMemberRepository
func (_mock *WorkspaceMemberRepository) Exists(ctx context.Context, workspaceID int, userID int) (bool, error) {
	ret := _mock.Called(ctx, workspaceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (bool, error)); ok {
		return returnFunc(ctx, workspaceID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = returnFunc(ctx, workspaceID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, workspaceID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceMemberRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type WorkspaceMemberRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID int
//   - userID int
func (_e *WorkspaceMemberRepository_Expecter) Exists(ctx interface{}, workspaceID interface{}, userID interface{}) *WorkspaceMemberRepository_Exists_Call {
	return &WorkspaceMemberRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, workspaceID, userID)}
}

func (_c *WorkspaceMemberRepository_Exists_Call) Run(run func(ctx context.Context, workspaceID int, userID int)) *WorkspaceMemberRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkspaceMemberRepository_Exists_Call) Return(b bool, err error) *WorkspaceMemberRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WorkspaceMemberRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, workspaceID int, userID int) (bool, error)) *WorkspaceMemberRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRole provides a mock function for the type WorkspaceMemberRepository
func (_mock *WorkspaceMemberRepository) FetchRole(ctc context.Context, workspaceID int, userID int) (domain.WorkspaceRole, error) {
	ret := _mock.Called(ctc, workspaceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchRole")
	}

	var r0 domain.WorkspaceRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (domain.WorkspaceRole, error)); ok {
		return returnFunc(ctc, workspaceID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) domain.WorkspaceRole); ok {
		r0 = returnFunc(ctc, workspaceID, userID)
	} else {
		r0 = ret.Get(0).(domain.WorkspaceRole)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctc, workspaceID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceMemberRepository_FetchRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRole'
type WorkspaceMemberRepository_FetchRole_Call struct {
	*mock.Call
}

// FetchRole is a helper method to define mock.On call
//   - ctc context.Context
//   - workspaceID int
//   - userID int
func (_e *WorkspaceMemberRepository_Expecter) FetchRole(ctc interface{}, workspaceID interface{}, userID interface{}) *WorkspaceMemberRepository_FetchRole_Call {
	return &WorkspaceMemberRepository_FetchRole_Call{Call: _e.mock.On("FetchRole", ctc, workspaceID, userID)}
}

func (_c *WorkspaceMemberRepository_FetchRole_Call) Run(run func(ctc context.Context, workspaceID int, userID int)) *WorkspaceMemberRepository_FetchRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkspaceMemberRepository_FetchRole_Call) Return(workspaceRole domain.WorkspaceRole, err error) *WorkspaceMemberRepository_FetchRole_Call {
	_c.Call.Return(workspaceRole, err)
	return _c
}

func (_c *WorkspaceMemberRepository_FetchRole_Call) RunAndReturn(run func(ctc context.Context, workspaceID int, userID int) (domain.WorkspaceRole, error)) *WorkspaceMemberRepository_FetchRole_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function for the type WorkspaceMemberRepository
func (_mock *WorkspaceMemberRepository) ListMembers(ctx context.Context, workspaceID int) ([]*domain.WorkspaceMember, error) {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []*domain.WorkspaceMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*domain.WorkspaceMember, error)); ok {
		return returnFunc(ctx, workspaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*domain.WorkspaceMember); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WorkspaceMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkspaceMemberRepository_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type WorkspaceMemberRepository_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID int
func (_e *WorkspaceMemberRepository_Expecter) ListMembers(ctx interface{}, workspaceID interface{}) *WorkspaceMemberRepository_ListMembers_Call {
	return &WorkspaceMemberRepository_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, workspaceID)}
}

func (_c *WorkspaceMemberRepository_ListMembers_Call) Run(run func(ctx context.Context, workspaceID int)) *WorkspaceMemberRepository_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkspaceMemberRepository_ListMembers_Call) Return(workspaceMembers []*domain.WorkspaceMember, err error) *WorkspaceMemberRepository_ListMembers_Call {
	_c.Call.Return(workspaceMembers, err)
	return _c
}

func (_c *WorkspaceMemberRepository_ListMembers_Call) RunAndReturn(run func(ctx context.Context, workspaceID int) ([]*domain.WorkspaceMember, error)) *WorkspaceMemberRepository_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type WorkspaceMemberRepository
func (_mock *WorkspaceMemberRepository) Remove(ctx context.Context, tx *sql.Tx, workspaceID int, userID int) error {
	ret := _mock.Called(ctx, tx, workspaceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, int, int) error); ok {
		r0 = returnFunc(ctx, tx, workspaceID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkspaceMemberRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type WorkspaceMemberRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - workspaceID int
//   - userID int
func (_e *WorkspaceMemberRepository_Expecter) Remove(ctx interface{}, tx interface{}, workspaceID interface{}, userID interface{}) *WorkspaceMemberRepository_Remove_Call {
	return &WorkspaceMemberRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, tx, workspaceID, userID)}
}

func (_c *WorkspaceMemberRepository_Remove_Call) Run(run func(ctx context.Context, tx *sql.Tx, workspaceID int, userID int)) *WorkspaceMemberRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *WorkspaceMemberRepository_Remove_Call) Return(err error) *WorkspaceMemberRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkspaceMemberRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, workspaceID int, userID int) error) *WorkspaceMemberRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}
